### ISSUE TITLE
Problem with memory

### ISSUE THREAD

**Issue by liyao880** [MarvinLer/tcga_weakly_MIL_WSI_segmentation#3]
Hi Marvin,

I'm trying to run the experiments on a WSI dataset similar to the TCGA one but got problem of OOM. In the paper, you said that 2 V100 NVIDIA GPUs were used for training. I'm using two Tesla V100-SXM2 gpus and allocated 16G memory for the program but get the problem of OOM. Could you share with me your experimental setting, such as how much memory you allocated for the experiments? Thanks!

Best,
Yao

**Comment by MarvinLer** [comment]
Hi,
Each time a WSI is sampled during training, a predetermined number of patches are retrieved and sent to the GPU for forward pass. In our experiments, we did sample 150 patches per WSI. This number of sampled patch is set with the command line argument `--max-bag-size`. By default, this argument is set to None, which implies that all patches from each WSI are retrieved which indeed saturates the GPU memory.

For clarity, instead of using e.g.
`python -m code.training --preprocessed-data-folder ./data/preprocessed --alpha 0.1 --beta 0.`
you could use
`python -m code.training --preprocessed-data-folder ./data/preprocessed --alpha 0.1 --beta 0. --max-bag-size 150`

Default value of `--max-bag-size` was changed in c68c3dfe0487cc52565bb28d81130f83864fa227 and set to 100 patches to avoid future GPU memory issues with default arguments.

Is it okay thereafter?

ML

**Comment by liyao880** [comment]
Thanks Marvin! I'll try that and let you know the outcome.

Best,
Yao

**Comment by dgonzMD** [comment]
Hi Marvin,

Excellent job. This is a fantastic repo and your paper is remarkable. Is there a way to skip the download step and perform preprocessing on an existing directory of WSI? Thanks!
