### ISSUE TITLE
Facing an Error :PermissionError: [Errno 13] Permission denied: './gdc-client'

### ISSUE THREAD

**Issue by lyl010221** [MarvinLer/tcga_weakly_MIL_WSI_segmentation#7]
Hello!Thank you for your outstanding work!
I was experiencing an error:  `PermissionError: [Errno 13] Permission Denied: './gdc-client'`  while running the code. 

`(venv) (pythonProject) lyl010221@ubuntu:~/PycharmProjects/pythonProject/tcga_segmentation$ python -m code.data_processing.main --gdc-executable ./gdc-client --manifest ./data/manifest_tcga_frozen_slides_breast_kidney_lung.txt data_processed`

This is the code I ran in Ubuntu based on the README. `./gdc-client` is the relative location of the gdc tool,`.txt` is the existing manifest file, and `data_processed` is the output folder's name

I have been tried some methods but don't work. Could you please help me to check the problem? Thank you very much!

**Comment by MarvinLer** [comment]
Hi, thanks for the kind words.
Seems to be an issue related to the execution rights of the `gdc-client` file.
Try something like `chmod +x gdc-client`, which should allow the python code to execute the file `gdc-client`

Best,
ML

**Comment by lyl010221** [comment]
Oh! Thank you for your quick answer! Your method can perfectly solve this problem!

But I seem to face a new error:`subprocess.CalledProcessError: Command '['./gdc-client', 'download', '--dir', 'data_processed/downloaded_slides', '--n-processes', '5', '00083f2c-c6aa-4e5f-9af0-945d8c9ff97b']' returned non-zero exit status 2.`

Is it my code `python -m code.data_processing.main --gdc-executable ./gdc-client --manifest ./data/manifest_tcga_frozen_slides_breast_kidney_lung.txt data_processed` wrong?

Thank you very much for your patient answers!

**Comment by MarvinLer** [comment]
No problem.

So what the code does actually is use the `gdc-client` file (program) which downloads slides from the TCGA website.
The python layer of calling the program (with `subprocess`) does not retrieve the error message of the `gdc-client`, so you should try to directly use the program without `subprocess` in a terminal e.g.:
`./gdc-client download --dir data_processed/downloaded_slides --n-processes 5 00083f2c-c6aa-4e5f-9af0-945d8c9ff97b`

I suspect you will get an error about something related to:
- either this is due to the fact that TCGA seems to have issues with their images (this has been going for some months now, and the images are still not available on their website e.g. https://portal.gdc.cancer.gov/files/4ecf5f2c-b095-423d-ace8-e24703fcc44a)
- or your `gdc-client` file is outdated (I suspect the managing team of TCGA updates the client from time to time for security issues) and in that case you should download a new `gdc-client` at https://gdc.cancer.gov/access-data/gdc-data-transfer-tool, unzip and paste/erase your old `gdc-client`

But I suspect the issue is the first one... which you and I cannot solve. I contacted the support some months ago, they were aware of the issue and were working on it but no news since then so if you have some, I'm all ears

Please let me know the error you have

**Comment by lyl010221** [comment]
```
ERROR: 00083f2c-c6aa-4e5f-9af0-945d8c9ff97b: 451 Client Error: UNAVAILABLE FOR LEGAL REASONS for url: https://api.gdc.cancer.gov/data/00083f2c-c6aa-4e5f-9af0-945d8c9ff97b: {"message":"Request contains a redacted file(s): ['00083f2c-c6aa-4e5f-9af0-945d8c9ff97b'], action not allowed"}

ERROR: 00083f2c-c6aa-4e5f-9af0-945d8c9ff97b: 451 Client Error: UNAVAILABLE FOR LEGAL REASONS for url: https://api.gdc.cancer.gov/data/00083f2c-c6aa-4e5f-9af0-945d8c9ff97b: {"message":"Request contains a redacted file(s): ['00083f2c-c6aa-4e5f-9af0-945d8c9ff97b'], action not allowed"}

ERROR: Unable to download file https://api.gdc.cancer.gov/data/00083f2c-c6aa-4e5f-9af0-945d8c9ff97b
Successfully downloaded: 0
Failed downloads: 1

```
Above are the error message I got after following your advice.It seems to be caused of the legal reason.Is it the first reason you suspect?

Thank you for your patient!

**Comment by MarvinLer** [comment]
Yes indeed, it says "Request contains a redacted file(s)" so the file is not available, i.e. what I suspected... Sorry got no more information about their situation, but it is problematic for me also!

**Comment by lyl010221** [comment]
Oh,what a pity! Hope they will improve it soon because the gdc is a convenient tool to download medical datasets!

Maybe I can try to avoid  this problem by collecting WSI by other way.

Thank you very much!

**Comment by MarvinLer** [comment]
No problem, good luck!

**Comment by nd26** [comment]
I am getting a similar error:
ERROR: 00083f2c-c6aa-4e5f-9af0-945d8c9ff97b: 403 Client Error: FORBIDDEN for url: https://api.gdc.cancer.gov/data/00083f2c-c6aa-4e5f-9af0-945d8c9ff97b: {"message":"You don't have access to this resource: Requested file 00083f2c-c6aa-4e5f-9af0-945d8c9ff97b does not allow read access"}

I know that this is not your fault (obvs!), but it would be amazing if you could create a new manifest file with files that are currently publicly accessible (based on the same concept of tumour vs normal WSIs for breast, kidney, etc. cancers).
